version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=burjodewa
      - POSTGRES_DB=burjos
      - POSTGRES_USER=postgres
    restart: always
    ports:
      - 9920:5432
    volumes:
      - db_data:/db_data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: